minor improvements

diff --git a/vedit b/vedit
--- a/vedit
+++ b/vedit
@@ -1,18 +1,25 @@
 #!/usr/bin/env bash
 
+if [[ $BASH_VERSION != 5.* ]]; then
+    echo >&2 "ERROR: This script requires bash version 5"
+    echo >&2 "Run: brew install bash"
+    exit 1
+fi
+
 set -Eeuo pipefail
 shopt -s inherit_errexit
 
-export createSecretOption="Create new secret..."
+export createSecretOption="Create new secret"
 
 function get_vault_path() {
     local path
     path="${1:-}"
+    upADir="../ (up a directory)"
 
     while [[ $path =~ /$ ]]; do
         new_path=$(
             vault kv list -format=json "${path}" |
-                jq --arg createSecret "$createSecretOption" -r '. + [ $createSecret ] | .[]' |
+                jq --arg createSecret "$createSecretOption" --arg upADir "$upADir" -r '[  $upADir, $createSecret ] + . | .[]' |
                 fzf --prompt="Path: ${path}" --preview="
             if [[ {} == '$createSecretOption' ]]; then
                 echo 'Create new secret...'
@@ -22,12 +29,25 @@ function get_vault_path() {
                 vault kv get -format=table '${path}{}' 
             fi"
         )
-        path="${path%/}/${new_path}"
+        if [[ ${new_path} == "$upADir" ]]; then
+            up_path="$(dirname "$path")/"
+            if [[ $up_path != "./" ]]; then
+                path="$up_path"
+            fi
+        else
+            path="${path%/}/${new_path}"
+        fi
     done
     echo "$path"
 }
 
 function main() {
+    if ! vault token lookup; then
+        echo >&2 "ERROR: Vault token not found"
+        echo >&2 "You can login with: vault login -method=ldap username=SSO_USERNAME"
+        exit 1
+    fi
+
     local path
     path=$(get_vault_path "${1:-${VEDIT_DEFAULT_KV_PATH:-secret/}}")
 
@@ -68,3 +88,4 @@ function main() {
 }
 
 main "${@}"
+
